# Site settings
title: tanner heffner
occupation: developer / designer
email: tannerjheffner@gmail.com
description: > # personal portfolio for tanner heffner. design, development, illustration, writing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tannerheffner.com" # the base hostname & protocol for your site
twitter_username: its_tanner
github_username:  tjheffner
linkedin_username: tannerheffner

# Build settings
markdown: kramdown
